### ISSUE TITLE
sh run/startALL.sh showing error

### ISSUE THREAD

**Issue by isolatedinformation** [StephanieWehner/QI-Competition2018#2]
Hi ! 
I have followed all the instructions given in the instrucction sheet . Nut when try to run SimulaQron using 
sh run/startAll.sh it shows the following error.
```
sh run/startAll.sh
python: can't open file 'SimulaQron/QI-Competition2018/SimulaQron/configFiles.py': [Errno 2] No such file or directory
sh: 0: Can't open SimulaQron/QI-Competition2018/SimulaQron/run/startVNodes.sh
sh: 0: Can't open SimulaQron/QI-Competition2018/SimulaQron/run/startCQCNodes.sh

```
P.S I have latest version of python , twisted and qutip installed.

**Comment by AckslD** [comment]
Hi!

I suspect you have not set the environment variables correct. It looks like your variable '$NETSIM' is set to 'SimulaQron/QI-Competition2018/SimulaQron'. Is this the case? Note that the path needs to be an absolute path. If for example these folders are in your home folder you can change the path to '~/SimulaQron/QI-Competition2018/SimulaQron'.

I hope this helps.

/Axel Dahlberg

**Comment by isolatedinformation** [comment]
Thank you very much ! It works now . The path was not an absolute one. That's why it was showing an error.
