### ISSUE TITLE
error in instructions document

### ISSUE THREAD

**Issue by aelmahdaoui** [StephanieWehner/QI-Competition2018#3]
In the instructions PDF, section 3.1.1 "An optimal quantum strategy", there is an error after the first formula saying "... where qubits a and c are held by Alice and b and c by Bob." 
c is mentioned twice

**Comment by stephendiadamo** [comment]
To align with the base example, it should be that 'a' and 'c' are with Alice and 'b' and 'd' are with Bob, but the subscripts above should switch 'b' with 'c'.

**Comment by aelmahdaoui** [comment]
Do you mean switch 'b' with 'c' and 'c' with 'b'?

**Comment by stephendiadamo** [comment]
I mean the 'c's on the left side of the tensor should be 'b's and the 'b's on the right side of the tensor should be 'c's.

**Comment by AckslD** [comment]
Hi!

Thanks for pointing this out! I will update the instructions.

/Axel Dahlberg
