### ISSUE TITLE
Question about starting SimulaQron

### ISSUE THREAD

**Issue by ghost** [StephanieWehner/QI-Competition2018#4]
Hello ! This might be a very simple question. I have tried to open SimulaQron on my computer (openSUSE 42.2) for the first time. But I ran into an error `kill: not enough arguments`. I am curious as to what might be causing this ?

I followed instructions from the instructions handout. Python 3 executes when I type python in my terminal. I have also installed `twisted`, `service_identity` and `qutip` using `pip` in a virtual environment. I have also double checked my path in which SimulaQron has been downloaded (which is Home). My environment variables were copied and pasted from the instructions handout as well (`export NETSIM=~/QI-Competition2018/SimulaQron
`, `export PYTHONPATH=~/QI-Competition2018:$PYHTONPATH
`). My problem is when I try to start SimulaQron using `sh run/startAll.sh` I end up with above error. 

Are there any other packages I should install ?

**Comment by AckslD** [comment]
Hello @PurvaAThakre !

This is actually not a problem. `run/startAll.sh` checks if the processes are already running and if so kills them. However if there are no running then on some operating systems this error will be printed. I will see if I can improve this but for now you can just ignore this error-message.

**Comment by ghost** [comment]
Thank you for your response ! I was able to run the automated tests.
